import { Product } from '@/types/product';

export const products: Product[] = [
  // FRAME-ONLY - Gọng riêng
  {
    id: 'f001',
    name: 'Gọng Titan Chữ Nhật Cổ Điển',
    type: 'frame-only',
    category: 'unisex',
    brand: 'VisionDirect',
    price: 890000,
    images: [
      'https://images.unsplash.com/photo-1716860836982-608d61f39be1?crop=center&fit=crop&w=800&h=600',
    ],
    description: 'Gọng kính titan siêu nhẹ với thiết kế chữ nhật cổ điển, phù hợp cho mọi khuôn mặt.',
    inStock: true,
    quantity: 45,
    allowPreOrder: false,
    frameSpecs: {
      material: 'titanium',
      frameWidth: 140,
      lensWidth: 52,
      lensHeight: 42,
      bridgeWidth: 18,
      templeLength: 145,
      weight: 18,
      colors: [
        { name: 'Đen', hex: '#000000' },
        { name: 'Xám Súng', hex: '#666666' },
        { name: 'Vàng Hồng', hex: '#B76E79' },
      ],
    },
    prescriptionCompatible: true,
    rating: 4.8,
    reviewCount: 127,
    tags: ['titan', 'nhẹ', 'sang trọng', 'unisex'],
    isPremium: false,
  },
  {
    id: 'f002',
    name: 'Gọng Mắt Mèo Acetate Nữ',
    type: 'frame-only',
    category: 'women',
    brand: 'VisionDirect',
    price: 690000,
    originalPrice: 890000,
    images: [
      'https://images.unsplash.com/photo-1764740113465-dc9e6b28cc9e?crop=center&fit=crop&w=800&h=600',
    ],
    description: 'Gọng acetate cao cấp với thiết kế mắt mèo quyến rũ, thể hiện phong cách nữ tính.',
    inStock: false,
    quantity: 0,
    allowPreOrder: false,
    frameSpecs: {
      material: 'acetate',
      frameWidth: 136,
      lensWidth: 50,
      lensHeight: 44,
      bridgeWidth: 20,
      templeLength: 140,
      weight: 24,
      colors: [
        { name: 'Đỏ Burgundy', hex: '#800020' },
        { name: 'Đen Bóng', hex: '#000000' },
        { name: 'Hồng Nude', hex: '#E8C4B8' },
      ],
    },
    prescriptionCompatible: true,
    rating: 4.6,
    reviewCount: 89,
    tags: ['mắt mèo', 'nữ tính', 'acetate', 'thời trang'],
    isPremium: false,
  },

  // COMPLETE-GLASSES - Kính hoàn chỉnh
  {
    id: 'cg001',
    name: 'Kính Cận Gọng Tròn Vintage',
    type: 'complete-glasses',
    category: 'unisex',
    brand: 'VisionDirect',
    price: 1290000,
    images: [
      'https://images.unsplash.com/photo-1764737719221-1776b8077d79?crop=center&fit=crop&w=800&h=600',
    ],
    description: 'Kính cận hoàn chỉnh với gọng tròn vintage và tròng kính chống ánh sáng xanh.',
    inStock: true,
    quantity: 32,
    allowPreOrder: true,
    frameSpecs: {
      material: 'metal',
      frameWidth: 134,
      lensWidth: 48,
      lensHeight: 48,
      bridgeWidth: 22,
      templeLength: 142,
      weight: 20,
      colors: [
        { name: 'Vàng Gold', hex: '#FFD700' },
        { name: 'Bạc', hex: '#C0C0C0' },
        { name: 'Đen Matte', hex: '#2C2C2C' },
      ],
    },
    includedLenses: {
      type: 'single-vision',
      material: 'cr39',
      coatings: ['anti-reflective', 'blue-light', 'scratch-resistant'],
      description: 'Tròng CR-39 chống ánh sáng xanh, chống phản chiếu',
    },
    prescriptionCompatible: false,
    rating: 4.9,
    reviewCount: 234,
    tags: ['vintage', 'tròn', 'blue light', 'hoàn chỉnh'],
    isPremium: false,
  },
  {
    id: 'cg002',
    name: 'Kính Đọc Sách Gọng Vuông TR90',
    type: 'complete-glasses',
    category: 'unisex',
    brand: 'VisionDirect',
    price: 990000,
    images: [
      'https://images.unsplash.com/photo-1716860836982-608d61f39be1?crop=center&fit=crop&w=800&h=600',
    ],
    description: 'Kính đọc sách với gọng TR90 siêu bền, tròng chống mỏi mắt.',
    inStock: true,
    quantity: 56,
    allowPreOrder: true,
    frameSpecs: {
      material: 'tr90',
      frameWidth: 138,
      lensWidth: 51,
      lensHeight: 40,
      bridgeWidth: 19,
      templeLength: 143,
      weight: 16,
      colors: [
        { name: 'Đen', hex: '#000000' },
        { name: 'Xanh Navy', hex: '#003366' },
      ],
    },
    includedLenses: {
      type: 'single-vision',
      material: 'cr39',
      coatings: ['anti-reflective', 'scratch-resistant'],
      description: 'Tròng CR-39 cơ bản chống phản chiếu',
    },
    prescriptionCompatible: false,
    rating: 4.7,
    reviewCount: 156,
    tags: ['đọc sách', 'TR90', 'bền', 'nhẹ'],
    isPremium: false,
  },

  // SUNGLASSES - Kính râm
  {
    id: 'sg001',
    name: 'Kính Râm Phi Công Classic',
    type: 'sunglasses',
    category: 'unisex',
    brand: 'VisionDirect Premium',
    price: 1590000,
    images: [
      'https://images.unsplash.com/photo-1599243439680-1af420953c23?crop=center&fit=crop&w=800&h=600',
    ],
    description: 'Kính râm phi công cổ điển với tròng phân cực chống UV400.',
    inStock: true,
    quantity: 28,
    allowPreOrder: true,
    frameSpecs: {
      material: 'metal',
      frameWidth: 142,
      lensWidth: 58,
      lensHeight: 52,
      bridgeWidth: 14,
      templeLength: 145,
      weight: 28,
      colors: [
        { name: 'Vàng Gold', hex: '#FFD700' },
        { name: 'Đen', hex: '#000000' },
        { name: 'Bạc', hex: '#C0C0C0' },
      ],
    },
    includedLenses: {
      type: 'single-vision',
      material: 'polycarbonate',
      coatings: ['polarized', 'uv-protection', 'scratch-resistant'],
      description: 'Tròng phân cực Polycarbonate chống UV400',
    },
    prescriptionCompatible: false,
    rating: 4.9,
    reviewCount: 312,
    tags: ['phi công', 'phân cực', 'UV400', 'cổ điển'],
    isPremium: true,
  },
  {
    id: 'sg002',
    name: 'Kính Râm Vuông Oversize Nữ',
    type: 'sunglasses',
    category: 'women',
    brand: 'VisionDirect',
    price: 1190000,
    images: [
      'https://images.unsplash.com/photo-1681147767903-9011e9bf9e83?w=600',
    ],
    description: 'Kính râm vuông oversize thời trang với gọng acetate cao cấp.',
    inStock: false,
    quantity: 0,
    allowPreOrder: true,
    frameSpecs: {
      material: 'acetate',
      frameWidth: 146,
      lensWidth: 56,
      lensHeight: 54,
      bridgeWidth: 18,
      templeLength: 145,
      weight: 32,
      colors: [
        { name: 'Đen Bóng', hex: '#000000' },
        { name: 'Nâu Tortoise', hex: '#8B4513' },
        { name: 'Xanh Dương', hex: '#1E3A8A' },
      ],
    },
    includedLenses: {
      type: 'single-vision',
      material: 'cr39',
      coatings: ['polarized', 'uv-protection'],
      description: 'Tròng phân cực chống UV',
    },
    prescriptionCompatible: false,
    rating: 4.6,
    reviewCount: 98,
    tags: ['oversize', 'vuông', 'nữ', 'thời trang'],
    isPremium: false,
  },

  // MORE PRODUCTS
  {
    id: 'f003',
    name: 'Gọng Kim Loại Mảnh Dáng Oval',
    type: 'frame-only',
    category: 'women',
    brand: 'VisionDirect',
    price: 590000,
    images: [
      'https://images.unsplash.com/photo-1749032712013-6f21d1be6a6c?w=600',
    ],
    description: 'Gọng kim loại mảnh nhẹ nhàng với dáng oval thanh lịch.',
    inStock: true,
    quantity: 67,
    allowPreOrder: false,
    frameSpecs: {
      material: 'metal',
      frameWidth: 132,
      lensWidth: 50,
      lensHeight: 38,
      bridgeWidth: 20,
      templeLength: 138,
      weight: 15,
      colors: [
        { name: 'Vàng Hồng', hex: '#E6A8A8' },
        { name: 'Bạc', hex: '#C0C0C0' },
      ],
    },
    prescriptionCompatible: true,
    rating: 4.5,
    reviewCount: 73,
    tags: ['oval', 'mảnh', 'nữ tính', 'nhẹ'],
    isPremium: false,
  },
  {
    id: 'cg003',
    name: 'Kính Đa Tròng Cao Cấp Progressive',
    type: 'complete-glasses',
    category: 'unisex',
    brand: 'VisionDirect Premium',
    price: 2490000,
    images: [
      'https://images.unsplash.com/photo-1715418554358-d34e420b18ab?w=600',
    ],
    description: 'Kính đa tròng progressive cao cấp cho người lão thị, chuyển tiếp mượt mà.',
    inStock: true,
    quantity: 18,
    allowPreOrder: true,
    frameSpecs: {
      material: 'titanium',
      frameWidth: 138,
      lensWidth: 52,
      lensHeight: 42,
      bridgeWidth: 18,
      templeLength: 145,
      weight: 19,
      colors: [
        { name: 'Đen', hex: '#000000' },
        { name: 'Nâu', hex: '#654321' },
      ],
    },
    includedLenses: {
      type: 'progressive',
      material: 'high-index',
      coatings: ['anti-reflective', 'blue-light', 'scratch-resistant', 'uv-protection'],
      description: 'Tròng High-Index 1.67 đa tròng Progressive với coating cao cấp',
    },
    prescriptionCompatible: false,
    rating: 5.0,
    reviewCount: 45,
    tags: ['progressive', 'lão thị', 'cao cấp', 'high-index'],
    isPremium: true,
  },
];

// Lens pricing configuration
export const lensPricing = {
  basePrice: {
    'single-vision': 500000,
    'bifocal': 800000,
    'progressive': 1200000,
  },
  materialUpcharge: {
    'cr39': 0,
    'polycarbonate': 200000,
    'high-index': 400000,
    'trivex': 300000,
    'glass': 100000,
  },
  coatingPrice: {
    'anti-reflective': 150000,
    'scratch-resistant': 100000,
    'uv-protection': 80000,
    'blue-light': 200000,
    'photochromic': 400000,
    'polarized': 350000,
  },
};

// Delivery time configuration (hours)
export const deliveryTimeConfig = {
  regular: 4,       // 4 giờ cho đơn thường
  preOrder: 48,     // 2 ngày cho pre-order
  prescription: 72, // 3 ngày cho prescription order
};
